version: "3.8"


# x-airflow-common:
#   &airflow-common
#   environment:
#     _PIP_ADDITIONAL_REQUIREMENTS: -r /requirements.txt
#   volumes:
#     - ./requirements.txt:/requirements.txt

services:
  postgres:
    image: postgres:15
    container_name: postgres-de
    environment:
      POSTGRES_DB: test_dwh
      POSTGRES_USER: de_user
      POSTGRES_PASSWORD: de_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  airflow-init:
    build: ./airflow
    #image: apache/airflow:2.7.2
    container_name: airflow-init
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://de_user:de_password@postgres:5432/test_dwh
      AIRFLOW__WEBSERVER__SECRET_KEY: "super_secret_key_for_local_dev"
    volumes:
      - ./dags:/opt/airflow/dags
    command: >
      bash -c "airflow db init && airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin"

  airflow-scheduler:
    build: ./airflow
    #image: apache/airflow:2.7.2
    container_name: airflow-scheduler
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://de_user:de_password@postgres:5432/test_dwh
      AIRFLOW__WEBSERVER__SECRET_KEY: "super_secret_key_for_local_dev"
    volumes:
      - ./dags:/opt/airflow/dags
    command: scheduler
    restart: always

  airflow-webserver:
    build: ./airflow
    #image: apache/airflow:2.7.2
    container_name: airflow-webserver
    depends_on:
      - airflow-scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://de_user:de_password@postgres:5432/test_dwh
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
      AIRFLOW__WEBSERVER__SECRET_KEY: "super_secret_key_for_local_dev"
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: webserver
    restart: always


  python-etl:
    build: ./python-etl
    container_name: python-etl
    depends_on:
      - postgres
    volumes:
      - ./etl_scripts:/app/etl_scripts

volumes:
  postgres_data: